[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  targetPort = 3998    # The port your frontend dev server runs on
  port = 8888          # Netlify Dev proxy port
  autoLaunch = false
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
