[build]
  command = "yarn install --ignore-engines && yarn run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--ignore-engines --network-timeout 1000000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"